### ISSUE TITLE
[BUG/ISSUE] Config 'class com.cerbon.bosses_of_mass_destruction.config.BMDConfig' has not been registered

### ISSUE THREAD

**Issue by ceifadorcinixtru** [CERBON-MODS/Bosses-of-Mass-Destruction-FORGE#1]
When i try to launch the mod i get this crash:

Caused by: java.lang.RuntimeException: Config 'class com.cerbon.bosses_of_mass_destruction.config.BMDConfig' has not been registered
	at me.shedaniel.autoconfig.AutoConfig.getConfigHolder(AutoConfig.java:77) ~[cloth-config-11.1.106-forge.jar%23510!/:?] {re:mixin,re:classloading}
	at com.cerbon.bosses_of_mass_destruction.entity.BMDEntities.<clinit>(BMDEntities.java:49) ~[BOMD-Forge-1.20.1-1.0.1.jar%23498!/:1.0.1] {re:mixin,re:classloading}

[crash-2023-11-27_16.44.33-client.txt](https://github.com/CERBON-MODS/Bosses-of-Mass-Destruction-FORGE/files/13479504/crash-2023-11-27_16.44.33-client.txt)

**Comment by NicolasCadre** [comment]
I can confirm I have the exact same crash and I have both cloth config and Geckolib latest version installed. I also uses Forge 47.2.1

**Comment by CerbonXD** [comment]
This error is really weird. I can't reproduce it. Anyway, would be possible for you to join my [discord](https://discord.gg/2PvYZfjWDf) and test a custom jar to help me fix the problem? I have an idea of what could be causing it, but I need someone that has the problem to test. If you can't, don't worry, just let me know.
